name: Polls-API CI

on:
  push:
    branch: [main]
  pull_request:
    branch: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: |
          docker build -t polls-api:latest .

      - name: Run image
        run: |
          docker run -d -p 5001:5001 --name polls-api-container polls-api:latest
          sleep 5
          curl http://localhost:5001/api/health || exit 1
