name: Polls-API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: |
          docker build --platform linux/amd64 -t polls-api:latest .

      - name: Run Container
        run: |
          docker run -d -p 5001:5001 --name polls-api-container polls-api:latest
          sleep 5
          curl http://localhost:5001/api/health || exit 1

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit test
        run: |
          pytest -v

      - name: Cleanup
        if: always()
        run: |
          docker stop polls-api-container
          docker rm polls-api-container

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Tag Docker image
        run: |
          docker tag polls-api cefiong/polls-api:latest
          docker tag polls-api cefiong/polls-api:${{ github.sha }}

      - name: Push docker image to Docker hub
        run: |
          docker push cefiong/polls-api:latest
          docker push cefiong/polls-api:${{ github.sha }}

      - name: Trigger Render redeploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
